name: flutter_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  lottie: ^3.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png             
    - assets/images/pp.jpg     
    - assets/images/lottie/dompetku.json  
